# VERSIÓN NUCLEAR - SOLO PARA DIAGNÓSTICO

availableSecrets:
  secretManager:
  - versionName: projects/fitness-464117/secrets/estaesunadieta/versions/latest
    env: 'GEMINI_API_KEY_CONTENT'

steps:
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - -c
  - |
    echo "Usando el secreto: $(echo $$GEMINI_API_KEY_CONTENT | cut -c 1-5)"