# ------------------------------------------------------------------
# PRUEBA DE FUEGO: Forzar un error nuevo y diferente
# ------------------------------------------------------------------

availableSecrets:
  secretManager:
  - versionName: projects/fitness-464117/secrets/estaesunadieta/versions/latest
    env: 'GEMINI_API_KEY_CONTENT'

steps:
# Paso 1: HE CAMBIADO EL NOMBRE DE LA HERRAMIENTA PARA FORZAR UN ERROR
# Si esta compilación falla con un error sobre "ESTO-DEBE-FALLAR", entonces el archivo se actualizó.
- name: 'gcr.io/cloud-builders/ESTO-DEBE-FALLAR' # <--- ¡¡¡EL CAMBIO ESTÁ AQUÍ!!!
  id: 'Build Docker Image'
  args: [
    'build',
    '--tag=gcr.io/${PROJECT_ID}/${_SERVICE_NAME}:${SHORT_SHA}',
    '--build-arg', 'API_KEY_FOR_BUILD=$$GEMINI_API_KEY_CONTENT',
    '.'
  ]

# He comentado el resto de los pasos para que el fallo sea inmediato.
# - name: 'gcr.io/cloud-builders/docker'
#   id: 'Push Docker Image'
#   args: ['push', 'gcr.io/${PROJECT_ID}/${_SERVICE_NAME}:${SHORT_SHA}']
#
# - name: 'gcr.io/cloud-builders/gcloud'
#   id: 'Deploy to Cloud Run'
#   args: [
#     'run', 'deploy', '${_SERVICE_NAME}',
#     '--image=gcr.io/${PROJECT_ID}/${_SERVICE_NAME}:${SHORT_SHA}',
#     '--region=${_REGION}',
#     '--platform=managed',
#     '--allow-unauthenticated',
#     '--port=8080'
#   ]

# Define las imágenes finales
images:
- 'gcr.io/${PROJECT_ID}/${_SERVICE_NAME}:${SHORT_SHA}'

# Define variables de sustitución
substitutions:
  _SERVICE_NAME: 'fitness'
  _REGION: 'us-central1'

# Define opciones de compilación
options:
  logging: CLOUD_LOGGING_ONLY