steps:
# Paso 1: Construir la imagen de Docker
- name: 'gcr.io/cloud-builders/docker'
  id: 'Build Docker Image'
  args: [
    'build',
    '--tag=gcr.io/${PROJECT_ID}/${_SERVICE_NAME}:${SHORT_SHA}',
    # --- AQUÍ ESTÁ EL CAMBIO ---
    '--build-arg', 'API_KEY_FOR_BUILD=$$GEMINI_API_KEY_CONTENT',
    '.'
  ]

# Paso 2: Publicar la imagen de Docker en el registro
- name: 'gcr.io/cloud-builders/docker'
  id: 'Push Docker Image'
  args: ['push', 'gcr.io/${PROJECT_ID}/${_SERVICE_NAME}:${SHORT_SHA}']

# Paso 3: Desplegar en Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  id: 'Deploy to Cloud Run'
  args: [
    'run', 'deploy', '${_SERVICE_NAME}',
    '--image=gcr.io/${PROJECT_ID}/${_SERVICE_NAME}:${SHORT_SHA}',
    '--region=${_REGION}',
    '--platform=managed',
    '--allow-unauthenticated',
    '--port=8080',
    '--set-env-vars=^#^NODE_ENV=production'
  ]

# ... el resto de tu archivo sigue igual